### ISSUE TITLE
Bug with node 18 and canvas

### ISSUE THREAD

**Issue by KozielGPC** [reviewdog/action-eslint#186]
I'm trying to run the workflow in a project where I have installed `"canvas": "^2.9.3"` and node 18, but when I run it I get the following error:

```
Run yarn install
yarn install v1.22.19
[1/[4](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:5)] Resolving packages...
warning Resolution field "puppeteer@14.0.0" is incompatible with requested version "puppeteer@^10.4.0"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > apollo-server-express@3.10.0" has unmet peer dependency "express@^4.17.1".
warning " > sqs-consumer@7.4.0" has unmet peer dependency "@aws-sdk/client-sqs@^3.428.0".
warning " > ts-loader@9.3.1" has unmet peer dependency "webpack@^[5](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:6).0.0".
[4/4] Building fresh packages...
error /home/runner/work/repository/repository/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments: 
Directory: /home/runner/work/repository/repository/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@18.13.0 | linux | x[6](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:7)4
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v10[8](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:9)-linux-glibc-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.[9](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:10).3/canvas-v2.9.3-node-v[10](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:11)8-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.3 and node@18.13.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-linux-glibc-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.13.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.13.0 | linux | x64
gyp info find Python using Python version 3.10.[12](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:13) found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v18.[13](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:14).0/node-v18.13.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.13.0/node-v18.13.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.13.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.13.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/work/repository/repository/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/.cache/node-gyp/18.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/runner/.cache/node-gyp/18.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/runner/.cache/node-gyp/18.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/repository/repository/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.2.0-10[14](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:15)-azure
gyp ERR! command "/opt/hostedtoolcache/node/18.13.0/x64/bin/node" "/opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/home/runner/work/repository/repository/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/runner/work/repository/repository/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /home/runner/work/repository/repository/node_modules/canvas
gyp ERR! node -v v18.13.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/hostedtoolcache/node/18.13.0/x64/bin/node /opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/runner/work/repository/repository/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/runner/work/repository/repository/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/runner/work/repository/repository/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:[16](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:17))
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 6.2.0-1014-azure
node-pre-gyp ERR! command "/opt/hostedtoolcache/node/[18](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:19).13.0/x[64](https://github.com/organization/repository/actions/runs/6614166635/job/17963534462#step:4:65)/bin/node" "/home/runner/work/repository/repository/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /home/runner/work/repository/repository/node_modules/canvas
node-pre-gyp ERR! node -v v18.13.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok 
Failed to execute '/opt/hostedtoolcache/node/18.13.0/x64/bin/node /opt/hostedtoolcache/node/18.13.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/runner/work/repository/repository/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/runner/work/repository/repository/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

### reviewdog.yml

```
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.13'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
```

**Comment by javierjulio** [comment]
This appears to be unrelated to this action because it's failing on yarn install, not the action.
